version: "3"
services:
  
  client:
   build:
      context: ./client
      dockerfile: Dockerfile
   ports:
    -  3000:3000
   container_name: week7-client
   networks:
    -  week7-stack-net
   volumes:
    -  ./client:/app
   depends_on:
    - backend
   environment:
     PORT: 3000
     DATABASE_URL: 'mongodb://admin:admin@mongo:27017/'
   stdin_open: true

  backend:
   build:
      context: ./backend
      dockerfile: Dockerfile
   ports:
     - 5000:5000
   container_name: week7-backend
   networks:
     - week7-stack-net
   volumes:
    - ./backend:/app
   depends_on:
    - db
   environment:
     PORT: 5000
     MONGODB_URI: 'mongodb://admin:admin@mongo:27017/'
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - week7-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  week7-stack-net:
   driver: bridge


volumes:
  mongo-data:
    driver: local



    