version: "3"
services:
  
  client:
   image: kndungi/yolo-client:1.0.0 
   ports:
    -  3000:3000
   container_name: week7-client
   volumes:
    -  ./client:/app
   depends_on:
    - backend
   environment:
     PORT: 3000
     
  backend:
   image: kndungi/yolo-backend:1.0.0
   ports:
     - 5000:5000
   container_name: week7-backend
   volumes:
    - ./backend:/app
   depends_on:
    - db
   environment:
     PORT: 5000
     MONGODB_URI: 'mongodb://admin:admin@mongo:27017/'
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db


volumes:
  mongo-data:
  



    