apiVersion: v1
kind: Service
metadata:
  name: week9-database-service
spec:
  selector:
    app: week9-database
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017